#!/usr/bin/env bash
# This script displays the content of /etc/passwd in a story format using a while loop and IFS

while IFS=: read -r username password user_id group_id user_info home_dir shell
do
  echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $user_info."
done < /etc/passwd

