#!/usr/bin/env bash
#script that loops from 1 to 10 and:displays bad luck for the 4th loop iteration displays good luck for the 8th loop iteration displays Best School for the other iterations
count=1
while [ $count -le 10 ]
do
  if [ $count -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((count++))
done

