#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1
while [ $i -le 10 ]
do
  if [ $i -eq 5 ]; then
    echo "Best School - Special Case for 5"
  elif [ $i -eq 8 ]; then
    echo "Best School - Special Case for 8"
  else
    echo "Best School"
  fi
  ((i++))
done
