#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20, with specific messages for 4th, 9th, and 17th loop iterations

i=1
while [ $i -le 20 ]
do
  case $i in
    4)
      echo "$i - bad luck from China"
      ;;
    9)
      echo "$i - bad luck from Japan"
      ;;
    17)
      echo "$i - bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  ((i++))
done
