#!/usr/bin/env bash
# This script displays the content of the current directory in list format, showing only the part of the name after the first dash

for file in *
do
  if [[ -f "$file" && "$file" != .* ]]; then
    new_name="${file#*-}"
    echo "$new_name"
  fi
done
