#!/bin/bash

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
done
