#!/usr/bin/env bash
#file 1
manage_process() {
    if [ "$1" == "start" ]; then
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
    elif [ "$1" == "stop" ]; then
        if [ -f /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm -f /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "Process not running"
        fi
    elif [ "$1" == "restart" ]; then
        $0 stop
        $0 start
        echo "manage_my_process restarted"
    else
        echo "Usage: manage_my_process {start|stop|restart}"
    fi
}

manage_process "$1"

